### ISSUE TITLE
application errror

### ISSUE THREAD

**Issue by aysegulucar2016** [ferhatkurt/openzeka#2]
Hi, 
We run 
./run-webserver-gpu.sh
web browser  http://localhost:5000/ is completely opened together with all figures.

but terminal shows some errors like as attached figure.

![img_6440](https://cloud.githubusercontent.com/assets/16757934/19401830/2fa0ea3c-9266-11e6-97de-09298c41a3d7.JPG)

What is problem? Is it Caffe installation problem? Could you please give an information about that problem?

previously many thanks

**Comment by ferhatkurt** [comment]
It is a Cuda Memory Error. I think you are using Jetson TK1. Jetson TK1 can run only one of web or API server beacuse default recognition model is big.
If you want to test the pycaffe install please open a terminal and
`python
import caffe
caffe.__version__`
If you see caffe version it means your device is ready for using caffe with python.

**Comment by aysegulucar2016** [comment]
It is ok. Thanks for your answers.
